# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "soundcloud"
name = "Soundcloud"
url = "https://soundcloud.com/renzwertig"

[social.params]
icon = "brand-soundcloud"

[[social]]
identifier = "apple"
name = "Apple Music"
url = "https://music.apple.com/artist/christian-renz/1612983248"

[social.params]
icon = "brand-apple"

[[social]]
identifier = "spotify"
name = "Spotify"
url = "https://open.spotify.com/artist/1Bm9n5jSbtH7D5brfvlLWf"

[social.params]
icon = "brand-spotify"
